### ISSUE TITLE
[Improves] New style

### ISSUE THREAD

**Issue by Lorenzobettega** [lcuis/search_choices#113]
I wanna change the way the chosen items are rendered, using something like a scrollable horizontal ListView, to show them:

![image](https://github.com/lcuis/search_choices/assets/84482292/d3da3dec-05cc-4fce-8d32-cfec48492428)

**Comment by Lorenzobettega** [comment]
This can also help in #40

**Comment by lcuis** [comment]
Hi @Lorenzobettega ,

Thanks for this.

It would be great to add this example here if possible.

Can you please explain a bit more how this would work?

We should still have the field with the hint displayed so that the user can click on it and the menu expands below the field as a scrollable row ListView as in your example?

The ListView would display the items with the tiled cross on their right as in your example in case of multiple choice mode and in case they are selected? Otherwise, the non-selected items and all the items in single choice mode would not have this tilted cross on their right?

Then, how should the selected items be displayed once the menu is closed?

**Comment by Macacoazul01** [comment]
@lcuis more or less like: https://pub.dev/packages/multi_dropdow

**Comment by lcuis** [comment]
Thanks a lot @Macacoazul01 !

I see much better now.

I have tried in the past to have the menu appear as an overlay and it didn't work. I'm not sure it would be easier today.

For the chips to display the selected results, that should be easy.

For the tilted cross to remove the selected results one by one, I don't think it is possible without modification.

**Comment by lcuis** [comment]
Hello @Lorenzobettega ,

I was able to build the list as a scrollable row of chips with a tilted cross to deselect the selected item from the results list.

Here is an example of the outcome:
![image](https://github.com/lcuis/search_choices/assets/32125299/c555e38b-8876-41b1-b568-d92ff9257608)

Can you please let me know whether this is what you were trying to get?

For the surrounding rounded box, you may want to try with the `fieldPresentationFn` or/and `fieldDecoration` parameters.

For the search results list to load in an overlay, this will require a serious modification of the project code and should probably still be referenced as #40 .

**Comment by Lorenzobettega** [comment]
Hi @lcuis, this is already a good help, thanks. About an overlay menu, no problem do in the way possible, I think that can be also a nice upgrade.

**Comment by lcuis** [comment]
Thanks for the confirmation @Lorenzobettega !
I agree that the overlay menu would be a nice upgrade.
