### ISSUE TITLE
RTL support - dropdown button has to be on the left side when RTL locale selected in app

### ISSUE THREAD

**Issue by slavap** [lcuis/search_choices#116]
![image](https://github.com/lcuis/search_choices/assets/4129763/d3f7ddad-7d56-441b-920d-975ca8b86539)

**Comment by lcuis** [comment]
Hi @slavap ,

Thanks a lot for raising this important issue.

I didn't realize that the field icons are not on the left when the ‘rightToLeft‘ parameter is set to ‘true‘. They clearly must.

I wish I could correct that now myself but I am on holiday for a few weeks without access to my development hardware.

I wonder whether this behavior should be applied automatically when the app language is RTL because I am not certain the widget text will be as well. This is why I would rather rely on the existing ‘rightToLeft‘ parameter. Does that seem acceptable to you @slavap ?

**Comment by slavap** [comment]
@lcuis 
Yes, for now explicit rightToLeft solves the problem:
```dart
SearchChoices.multiple(
      rightToLeft: Directionality.maybeOf(context) == TextDirection.rtl,
```
But I would say it should be default "automatic" behavior.

**Comment by lcuis** [comment]
Thanks for your reply @slavap .

Then I will look into this rtl automatic adaptation as soon as I can.

**Comment by slavap** [comment]
@lcuis Thank you!

**Comment by lcuis** [comment]
Hello @slavap ,

Version 2.2.6 published yesterday should automatically adapt the rtl parameter based on the app.

**Comment by lcuis** [comment]
Thanks @slavap for creating the issue, for the solution code and for the confirmation!
