### ISSUE TITLE
How to automatically open the dropdown after page loading?

### ISSUE THREAD

**Issue by jibaud** [lcuis/search_choices#48]
Hi, I'd like to avoid the user to tap on the dropdown to display the search input. Is it possible to focus the input directly after the page loading? Thanks.

**Comment by lcuis** [comment]
Hello @jibaud ,

I think this should be possible with the help of `setOpenDialog` parameter.
This allows you to set the function to call in order to open the menu.
The example works with a dialog box when pressing a button:
```dart
SearchChoices.single(
        label: Column(
          children: items.map((item) {
            return (ElevatedButton(
              child: item.child,
              onPressed: () {
                openDialog!(item.value.toString());
              },
            ));
          }).toList(),
        ),
        items: items,
        value: selectedValueSingleDialog,
        hint: "Select one",
        searchHint: "Select one",
        onChanged: (value) {
          setState(() {
            selectedValueSingleDialog = value;
          });
        },
        isExpanded: true,
        setOpenDialog: (externalOpenDialog) {
          openDialog = externalOpenDialog;
        },
      )
```
[Single dialog open and set search terms example gif](https://camo.githubusercontent.com/652262f6b497793e53052c8df72a390fca6a2e9783fb85c28e0cf56354cfa029/68747470733a2f2f73656172636863686f696365732e6a6f642e6c692f53696e676c652532306469616c6f672532306f70656e253230616e642532307365742532307365617263682532307465726d732e676966)

Here is an example that works with a menu:

```dart
SearchChoices.single(
        dialogBox: false,
        items: items,
        value: selectedValueSingleDialog,
        hint: "Select one",
        searchHint: "Select one",
        onChanged: (value) {
          setState(() {
            selectedValueSingleDialog = value;
          });
        },
        isExpanded: true,
        setOpenDialog: (externalOpenMenu) {
          openMenu = externalOpenMenu;
        },
        menuConstraints: BoxConstraints.tight(Size.fromHeight(350)),
      )
```

In order to actually open the menu when the page loads, you may want to add either:
1. this to the end of the `initState`:
```dart
WidgetsBinding.instance!.addPostFrameCallback((_) => openMenu!(""));
```
or

2. this with some additional conditions (for example if the choice is not made) towards the end of the `build` function:
```dart
Future.delayed(Duration(milliseconds: 500)).whenComplete((){openMenu!("");});
```

I hope this will work for you.

**Comment by jibaud** [comment]
Thank you very much! 🙏

**Comment by lcuis** [comment]
You’re welcome @jibaud !
