### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by krButani** [lcuis/search_choices#95]
Hi @lcuis,

We found another issue.

RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _DropdownDialogState.listWithPagination.<anonymous closure> (package:search_choices/search_choices.dart:2992:24)

**Comment by lcuis** [comment]
Hi @krButani ,

Thanks for reporting this issue.
If I am not mistaken, the line referred to is the following one:
```dart
widget.items![index] as DropdownMenuItem<T>,
```
Since the error message mentions an empty range of valid values, it is likely that the `items` parameter is an empty list. Is this the possible cause of this issue?

**Comment by krButani** [comment]
but I used emptyListWidget: () => Text("No result found."). So, its display Text Widget right.

**Comment by lcuis** [comment]
Maybe the name of the parameter `emptyListWidget` is misleading. It is not meant to handle the case of an empty list of items while there is a selected value. Instead, it will display a custom message when the search returns no result.

I have 2 questions that may help solving this issue:
1. Is there a selected value?
2. Is the list of items empty?

**Comment by lcuis** [comment]
Ok, I think I understand the issue then.
At the moment, the `search_choices` plugin is not meant to handle such case gracefully. This is because, IMHO, the developer must know there is an issue with the data in case the selected value is not in the list when this is not intentional. I believe it would be more complex to introduce a special case to the plugin than handling it from the calling code. Do you think it would be possible to call SearchChoices widget with a null selected value in case the list of items is empty? Maybe something like that:
```dart
...
items: myItems,
value: myItems.isEmpty?null:mySelectedValue,
...
```

**Comment by krButani** [comment]
Its not working. I think we used displayItem: so, its came this error

**Comment by krButani** [comment]
I got this issue we use selectedValueWidgetFn widget so, that way it came sorry we bother. Its our developer mistake.

**Comment by lcuis** [comment]
Glad it's working. Thanks for the confirmation!
